name: Analyze and test

defaults:
  run:
    working-directory: glados

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --line-length=80 --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Prepare coverage package
        run: dart pub global activate coverage

      - name: Run tests with coverage
        run: dart pub global run coverage:test_with_coverage
